# Header
menu:
  Home: /
  Archives: /archives
#  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloudq
- archive

# Contacts
contacts:
  github: http://github.com/s-oravec
  twitter: 's_oravec'
  # facebook: '#'
  # dribbble: '#'
  rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
# google_plus:
# fb_admins:
# fb_app_id:

